Nature/Controllers/AuthorizeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Nature.Controllers
{
    public class AuthorizeController : Controller
    {
        DcDataContext dc = new DcDataContext();

        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(string Username, string Password)
        {
            if (Convert.ToBoolean(dc.v_Check_Password(Username, Password)))
            {
                Session["Username"] = Username;
                return RedirectToRoute(new { controller = "Private", action = "Index" });
            }
            else
            {
                ViewBag.Message = "نام کاربری یا کلمه عبور اشتباه است";
                return View();
            }

        }
        [Authenticate]
        public ActionResult Logout()
        {
            Session["Username"] = null;
            return RedirectToAction("Login");
        }
    }
}

Nature/Controllers/PrivateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Nature.Controllers
{
    [Authenticate]
    public class PrivateController : Controller
    {
        // GET: Private
        public ActionResult Index()
        {
            return View();
        }
    }
}

Nature/Views/Shared/Private.cshtml
@{
    ViewBag.Title = "سامانه مدیریت محتوی" + Nature.App_Code.About.AppName;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="Menu">
    @Html.ActionLink("خروج","Logout", "Authorize")
</div>
<div class="Body">
@RenderBody()
</div>

Nature/Views/Shared/Public.cshtml
@{
    ViewBag.Title = Nature.App_Code.About.AppName;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="Body">
@RenderBody()
</div>

Nature/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="author" content="Sharifi">
    <title>@ViewBag.Title</title>
    <link href="~/Content/Theme/jquery-ui.css" rel="stylesheet" />
    <link href="~/Content/_Layout.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="~/@("Content/" + HttpContext.Current.Request.RequestContext.RouteData.Values["controller"] + "/" + @HttpContext.Current.Request.RequestContext.RouteData.Values["action"] +".css")" />
    <script src="~/Scripts/_Layout.js"></script>
    <script src="~/@("Scripts/" + HttpContext.Current.Request.RequestContext.RouteData.Values["controller"] + "/" + @HttpContext.Current.Request.RequestContext.RouteData.Values["action"] +".js")"></script>
</head>
<body style="direction:rtl">
    @try
    {
        if (ViewBag.Message != null && ViewBag.Message != "")
        {
            <div class="Message">
                @Html.Raw(ViewBag.Message)
            </div>
        }
    }
    catch { }
    <header>
        <h1>@Nature.App_Code.About.AppName</h1>
    </header>
    @RenderBody()
    <footer>
        برخی از حقوق محفوظ است © @DateTime.Now.Year
    </footer>
</body>
</html>